apiVersion: v1
kind: Service
metadata:
  labels:
    app: imageswap-webhook
    resource: service
  name: imageswap
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    targetPort: 5000
  selector:
    app: imageswap
  sessionAffinity: None
  type: ClusterIP
