apiVersion: v1
kind: Pod
metadata:
  labels:
    run: toolbox
  name: test-pod02
spec:
  containers:
    - name: hello-kubernetes
      image: paulbouwer/hello-kubernetes:1.5
      ports:
      - containerPort: 8080
