apiVersion: v1
kind: Service
metadata:
  labels:
    app: imageswap-webhook
  name: imageswap-webhook-svc
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    targetPort: 5000
  selector:
    app: imageswap-webhook
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageswap-webhook
  labels:
    app: imageswap-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageswap-webhook
  template:
    metadata:
      labels:
        app: imageswap-webhook
    spec:
      containers:
      - name: imageswap-webhook
        image: jmsearcy/imageswap-webhook
        ports:
        - containerPort: 5000
        command: [/app/imageswap-webhook.py]
        imagePullPolicy: Always
        env:
        - name: TMUS_IMAGE_REPO
          value: jmsearcy
        - name: FLASK_ENV
          value: development
        volumeMounts:
          - name: script
            mountPath: /app
          - name: httpssl
            mountPath: /app/ssl
            readOnly: true
      volumes:
        - name: script
          configMap:
            name: imageswap-webhook-script
            defaultMode: 0755
            items:
              - key: script
                path: imageswap-webhook.py
        - name: httpssl
          secret:
            secretName: imageswap-webhook-ssl
---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: imageswap-webhook
webhooks:
  - name: imageswap-webhook.k8s.t-mobile.com
    clientConfig:
      service:
        name: imageswap-webhook-svc
        namespace: default
        path: "/"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHhPREV3TVRrdwpORFV5TkRKYUZ3MHpPREV3TVRrd05EVXlOREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFETHI0K1ZjRC9UNjlrY0xYZmtRbjZEalBsNDg5L0NLY1kzQ01PaXBYNDU0R1BCSlRHTQpMOVpLMlFrTCthVmN5WmJtdmZMWFI0dWtIMG1iK05TMzdtKzQxRzZmQXhrV2JWc2N6ZTM5QmdOcFlYK0dKWXhUCmNoUG83b3U5d2IrNHlwREVhK0h3L3dLL3BBTFBid0t4ZzBvbTgrY2trQ1p3VDEyWXNNTFN2djEyKzJSQXFQSXkKdGF3V2ZkTEVmU0l1QjV1ZlZLSFd1S3g5ZzRxdnJpakVCa0QrbENHODZYeHJoV3U3NllmNlNRY2lSOGZlWXZPdQpwRk1kNFprQTZYc0cyc3lFR09SUnZKWDE3ZCt2MEZsVzhIaWlmQnVmV0xKenlJcFpaT1VOWGVCR1B2TkFGK3NJCndHRisxYmNJVzJ0UXVjQ21mMnRJSGQzRXNlcVVYbUdLdWVoSEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFSV0F3ZGZBK2Q1b3V4dVh3Two0c2xhOEZ6VUREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFiSmY2Smw1WTU4M0poSTc4dWVvSmdhU3JSMkl1Ck15OXlNQS9kZ09VeU5ocUE1Vmg4T2JnWDFRcGdkTzB6QUFyUkVpVThqMlNJRXhWL3JSSWwvVG82a1F0NVBvZjgKUzVJcTF0YTUySWRuTzhSUFZFbE42K1lvbS9hVUJ1ZlFLbE81MmV3QlVSR0dUZUxza2crL0xKSXV4TnQ3enc4dwpYN0I4YUpiTEw5Z3ZId2F0azhEekJhSDQrTXl6NWd0MThFN09xeXhkbEI5dVdYN25GUnpxUk8vOVNkVGk1VzZNCnFKVGd4OWZpaXBoWkdKdzF2RUpsVHJDeVFsdzB5akhyaWtlTGpjK0x4bnVzY2J1NSt1OVYwQkNoU2JFL1lTRmcKWmNsTHN1Mm9naGI3UmNKNzkvamdyRzZkUU1rOXZiT0hzYTFNVzVERWgybFhPSGhqZ1ZFRUQxWDFqdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KCg=="
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - "*"
        apiVersions:
          - "v1
        resources:
          - "pod"
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        swapme: "enabled"
