apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageswap-webhook
  labels:
    app: imageswap-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageswap-webhook
  template:
    metadata:
      labels:
        app: imageswap-webhook
    spec:
      containers:
      - name: imageswap-webhook
        image: jmsearcy/python3-flask:latest
        ports:
        - containerPort: 5000
        command: [/app/imageswap-webhook.py]
        imagePullPolicy: Always
        env:
        - name: IMAGE_PREFIX
          value: jmsearcy
        - name: FLASK_ENV
          value: development
        volumeMounts:
          - name: script
            mountPath: /app
          - name: certs
            mountPath: /app/ssl
            readOnly: true
      volumes:
        - name: script
          configMap:
            name: imageswap-webhook-cm
            defaultMode: 0755
            items:
              - key: script
                path: imageswap-webhook.py
        - name: certs
          secret:
            secretName: imageswap-webhook-certs
