apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy04
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      initContainers:
      - name: hello-kubernetes-init
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
